service: sudoku-server

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-offline
  - serverless-python-requirements

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
