service: sudoku-scanner

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rekognition:DetectText"
      Resource: "*"

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-offline
  - serverless-python-requirements

functions:
  scan-sudoku:
    handler: handler.scan_sudoku
    events:
      - http:
          path: /scan-sudoku
          method: POST
